const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const root=path.resolve(__dirname,'..');
const archive={filename:'fixture.xlsx',weeks:[{week:'2026-01-05',month:'JANEIRO',title:'GORJETAS 5 a 11',daily:70,days:Array(7).fill(10),fields:[{column:'C',label:'Staff'},{column:'D',label:'H'},{column:'E',label:'€'},{column:'F',label:'0.05'},{column:'G',label:'€-5%'}],staff:[{name:'Pessoa <teste>',cells:[{cell:'C16',value:'Pessoa <teste>'},{cell:'D16',value:40},{cell:'E16',value:59.9974025974026,formula:'=D16*E34'},{cell:'F16',value:2.7474025974026},{cell:'G16',value:57.25,formula:'=E16-F16'}]}],totals:[{cell:'C17',value:'TOTAL'},{cell:'D17',value:40},{cell:'E17',value:70}]},{week:'2026-02-02',month:'FEVEREIRO',title:'GORJETAS 2 a 8',daily:140,days:Array(7).fill(20),fields:[],staff:[],totals:[]}],months:[{month:'JANEIRO',cells:[{cell:'AE23',value:'DEVOLVER 10€'}]}]};
const server=http.createServer((req,res)=>{const url=req.url.split('?')[0],file=path.resolve(root,'.'+(url==='/'?'/index.html':url));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.mjs')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
(async()=>{const {archivePayment}=await import('../tips-archive.mjs');
 const person={gross:100,cells:[{cell:'G1',value:95},{cell:'H1',value:90},{cell:'I1',value:110}]};
 assert.equal(archivePayment(person,[{column:'G',label:'€-5%'}]),95);
 assert.equal(archivePayment(person,[{column:'G',label:'€-5%'},{column:'H',label:'€-5%'}]),90);
 assert.equal(archivePayment(person,[{column:'G',label:'€-5%'},{column:'I',label:'Total '}]),110);
 assert.equal(archivePayment(person,[]),100);
 assert.equal(archivePayment({gross:100,cells:[{cell:'G1',value:0}]},[{column:'G',label:'€-5%'}]),0);
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const mock=`export function createClient(){const query={select(){return query},eq(){return query},order(){return query},range:async()=>({data:[]}),maybeSingle:async()=>({data:{revision:1,state:{staff:[],weeks:[],draft:null,excel_archive:${JSON.stringify(archive)}}}})};return {auth:{getSession:async()=>({data:{session:{user:{id:'test'}}}}),onAuthStateChange:cb=>window.logoutArchive=()=>{window.__signedOut=true;cb('SIGNED_OUT')},},from:()=>query};}`.replace("getSession:async()=>({data:{session:{user:{id:'test'}}}})","getSession:async()=>({data:{session:window.__signedOut?null:{user:{id:'test'}}}})");
 await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:mock}));await page.goto('http://127.0.0.1:'+server.address().port);
 assert.equal(await page.locator('#gt-history-view').isVisible(),false);await page.locator('#gt-view-history').click();await page.getByText('Histórico do Excel · 2 semanas',{exact:true}).click();assert.equal(await page.locator('[data-archive-weeks] > details').count(),2);
 await page.locator('[data-archive-month]').selectOption('JANEIRO');assert.equal(await page.locator('[data-archive-weeks] > details').count(),1);await page.locator('[data-archive-weeks] > details > summary').click();assert((await page.locator('[data-archive-weeks]').textContent()).includes('60'));assert((await page.locator('.tips-record-amount').textContent()).includes('57,25'));assert((await page.locator('.tips-record-amount').textContent()).includes('Após acerto'));assert.equal(await page.locator('[data-archive-weeks] teste').count(),0);assert((await page.locator('[data-archive-source]').textContent()).includes('DEVOLVER 10€'));
 await page.locator('[data-archive-overview]').click();assert((await page.locator('#gt-overview').textContent()).includes('57,25'));assert.equal(await page.locator('#gt-overview li').count(),1);assert((await page.locator('#gt-overview li').textContent()).includes('Pessoa <teste>'));await page.locator('[data-overview-close]').click();
 for(const width of [320,390,780]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 if(process.env.TIPS_HISTORY_SCREENSHOT){await page.setViewportSize({width:390,height:844});await page.screenshot({path:process.env.TIPS_HISTORY_SCREENSHOT,fullPage:true});}
 await page.evaluate(()=>window.logoutArchive());await page.locator('#auth').waitFor({state:'visible'});assert.equal(await page.locator('#gt-excel').textContent(),'');assert.deepEqual(errors,[]);console.log('PASS: historical source is shown, month filters work, precision/source notes are retained, text is escaped, mobile layout and signout isolation work.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
