const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const base=path.resolve(__dirname,'..');
const mock=`import {calculate} from '/tips-core.mjs';
let ledger={revision:0,state:{staff:[],weeks:[],draft:null}},calls=0;
window.__tipTest={get ledger(){return ledger},get calls(){return calls}};
export function createClient(){return {auth:{getSession:async()=>({data:{session:{user:{id:'test-user'}}}}),onAuthStateChange:()=>{}},from(name){let q={select(){return q},eq(){return q},order(){return q},range(){return Promise.resolve({data:[],count:0,error:null})},maybeSingle(){return Promise.resolve({data:ledger,error:null})}};return q;},async rpc(name,args){calls++;if(args.p_revision!==ledger.revision)return {error:{message:'Dados mudaram'}};let s=structuredClone(ledger.state),p=args.p_payload;if(args.p_action==='add_staff'){s.staff.push({id:'p'+(s.staff.length+1),name:p.name,balance:p.opening,opening:p.opening,opening_note:p.opening_note,active:true,retain:p.retain,linked:p.linked});if(s.draft)s.draft.entries.push({id:s.staff.at(-1).id,minutes:0,retain:p.retain,leaving:false,paid:null});}if(args.p_action==='save_draft')s.draft=p;if(args.p_action==='confirm'){const result=calculate(p,s.staff);s.weeks.push({...p,total:result.total,daily:result.daily,close:result.close,payments:result.payments,confirmed_at:new Date().toISOString()});for(const person of s.staff){const payment=result.payments.find(x=>x.id===person.id);if(payment){person.balance=payment.balance;person.active=!payment.leaving;}}s.draft=null;}ledger={revision:ledger.revision+1,state:s};return {data:ledger,error:null};}};}`;
const server=http.createServer((req,res)=>{const file=path.join(base,decodeURIComponent(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!file.startsWith(base+path.sep)){res.writeHead(403).end();return;}if(!fs.existsSync(file)){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.mjs')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.setDefaultTimeout(7000);page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE:',e.message)});page.on('requestfailed',r=>console.error('REQUEST:',r.url(),r.failure()?.errorText));await page.route('https://cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:mock.replace("'/tips-core.mjs'",JSON.stringify("http://127.0.0.1:"+server.address().port+"/tips-core.mjs"))}));await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#gt-week').fill('2026-09-21');await page.locator('#gt-week').dispatchEvent('change');await page.getByRole('button',{name:'2. Equipa',exact:true}).click();
for(const person of [{name:'A',opening:'4.35',retain:true},{name:'B',opening:'3.20',retain:true},{name:'Extra',opening:'0',retain:false}]){await page.locator('#gt-new > summary').click();await page.locator('#gt-name').fill(person.name);await page.locator('#gt-retain').setChecked(person.retain);if(!await page.locator('#gt-opening').isVisible())await page.locator('#gt-person-form details summary').click();await page.locator('#gt-opening').fill(person.opening);await page.locator('#gt-opening-note').fill('Saldo de teste');await page.locator('#gt-person-form button').click();await page.waitForFunction(()=>!document.querySelector('#team-tips').classList.contains('tips-loading'));}
// Adding people preserves the week. Set explicit fixture week and inputs again.
await page.getByRole('button',{name:'1. Valores',exact:true}).click();await page.locator('#gt-week').fill('2026-09-21');await page.locator('#gt-week').dispatchEvent('change');
for(const [i,v] of ['50','35','40','55','60','80','80'].entries())await page.locator('[data-day="'+i+'"]').fill(v);
await page.getByRole('button',{name:'Continuar para equipa',exact:true}).click();for(const [id,v] of [['p1','40'],['p2','32'],['p3','8']])await page.locator('[data-hours="'+id+'"]').fill(v);
await page.getByRole('button',{name:'Rever pagamentos',exact:true}).click();assert.equal(await page.locator('[data-paid="p1"]').inputValue(),'190.00');assert.equal(await page.locator('[data-paid="p3"]').inputValue(),'40.00');
await page.locator('[data-paid="p1"]').fill('194');await page.locator('[data-paid="p1"]').press('Tab');assert((await page.locator('#gt-totals').textContent()).includes('386,00'));
await page.locator('#gt-statement-open').click();assert((await page.locator('#gt-statement').textContent()).includes('PREPARAÇÃO'));assert((await page.locator('#gt-statement').textContent()).includes('194,00'));await page.locator('#gt-statement [data-close]').click();
await page.locator('#gt-save-draft').click();await page.waitForFunction(()=>window.__tipTest.ledger.revision===4);await page.locator('#gt-refresh').click();await page.waitForFunction(()=>!document.querySelector('#team-tips').classList.contains('tips-loading'));assert.equal(await page.locator('[data-paid="p1"]').inputValue(),'194.00');
await page.locator('#gt-review').click();await page.locator('#gt-confirm').click();await page.waitForFunction(()=>window.__tipTest.ledger.state.weeks.length===1);assert.equal(await page.evaluate(()=>window.__tipTest.ledger.state.staff[0].balance),1035);assert.equal(await page.locator('#gt-week').inputValue(),'2026-09-28');
await page.locator('#gt-view-history').click();await page.locator('.tips-history > summary').last().click();await page.locator('#gt-history > details > summary').click();await page.locator('[data-statement-week="2026-09-21"]').click();assert((await page.locator('#gt-statement').textContent()).includes('Pagamentos registados'));await page.evaluate(()=>{window.print=()=>window.__printed=true;});await page.locator('#gt-statement [data-print]').click();assert(await page.evaluate(()=>window.__printed));assert((await page.locator('#tips-printout').textContent()).includes('194,00'));await page.locator('#gt-statement [data-close]').click();
const backupPromise=page.waitForEvent('download');await page.locator('#gt-backup').click();const backup=await backupPromise,backupPath=await backup.path(),backupData=JSON.parse(fs.readFileSync(backupPath,'utf8'));assert.equal(backupData.state.weeks.length,1);assert.equal(backupData.state.staff[0].balance,1035);
await page.locator('#gt-view-week').click();assert.equal(await page.locator('#gt-history-view').isVisible(),false);
await page.getByRole('button',{name:'1. Valores',exact:true}).click();for(const [i,v] of ['50','35','40','55','60','80','80'].entries())await page.locator('[data-day="'+i+'"]').fill(v);await page.getByRole('button',{name:'Continuar para equipa',exact:true}).click();for(const [id,v] of [['p1','40'],['p2','32'],['p3','8']])await page.locator('[data-hours="'+id+'"]').fill(v);await page.getByRole('button',{name:'Rever pagamentos',exact:true}).click();assert.equal(await page.locator('[data-paid="p1"]').inputValue(),'210.35');
await page.locator('[data-paid="p1"]').fill('210');await page.locator('[data-paid="p1"]').press('Tab');assert(await page.locator('#gt-review').isDisabled());await page.locator('#gt-suggestions').click();assert.equal(await page.locator('[data-paid="p1"]').inputValue(),'210.35');
if(process.env.TIPS_SCREENSHOT)await page.screenshot({path:process.env.TIPS_SCREENSHOT,fullPage:true});
for(const width of [320,390,780]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Overflow '+width);}
assert.deepEqual(errors,[]);console.log('PASS: actual app navigation, team creation, values/hours, overrides, draft reload, confirmation, balance update, month-end guard, mobile layouts; mocked transport.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
